export enum QueryKey {
  REGIONS = "REGIONS",
  CITY = "CITY",
  AREAS = "AREAS",
  CATEGORIES = "CATEGORIES",
  PRODUCTS = "PRODUCTS",
  BANNER = "BANNER",
  SINGLE_PRODUCT = "SINGLE_PRODUCT",
}
